### ISSUE TITLE
Auto pick the first or let the user choose

### ISSUE THREAD

**Issue by topher-nullset** [QuantumWarpCode/yt-dlp-dearrow#3]
I was thinking of a version that lists the options present from DeArrow and lets the user choose; though I don't want to override the natural functionality of picking the first when this is used as a part of a script. Just unsure at this point if i can use flags of some kind.

**Comment by QuantumWarpCode** [comment]
I think we can with the kwargs pointer that gets passed to the plugin. Let me message the yt-dlp team.

**Comment by QuantumWarpCode** [comment]
Added in commit https://github.com/QuantumWarpCode/yt-dlp-dearrow/commit/2e46eca7b2242d8c9765bf2d12f92270b694be64
